//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHotelReservation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public int Id { get; set; }
        public int NumBeds { get; set; }
        public bool View { get; set; }
        public bool Smoker { get; set; }
        public double BasicPrice { get; set; }
        public int MaxOccupancy { get; set; }
    }
}
